#!/bin/bash
# /etc/init.d/switchgearsXFD
# Debian on Raspberry Pi compatible XFD startup script, Device Discovery Server.
# info@switch-gears.dk
#
### BEGIN INIT INFO
# Provides:          XFD_discover
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start XFD at boot time
# Description:       Jumpstarts the server that the jenkins plugin can use to find the lamp
### END INIT INFO

DESC="Switch-Gears.dk eXtreme Feedback Device Discovery Server"
NAME=switchgearsXFDDiscoveryServer
SCRIPTNAME=/etc/init.d/$NAME
PIDFILE=/tmp/xfd/discover-xfd.pid

if [ `id -u` -ne 0 ]; then
    echo "The $NAME init script can only be run as root"
    exit 1
fi

do_start()
{
    mkdir -p $(dirname $PIDFILE)
    rm -f $PIDFILE
    sudo /home/pi/extremefeedbacklamp/xfd_discovery_server.py &
    echo -n $! > $PIDFILE
}

do_stop()
{
    if [ -f $PIDFILE ]; then
        kill `cat $PIDFILE`
    fi
}

case "$1" in
  start)
    echo "Starting $NAME"
    do_start
    ;;
  stop)
    echo "Stopping $NAME"
    do_stop
    ;;
  restart)
    echo "Stopping $NAME"
    do_stop
    do_start
    ;;
  status)
    if [ -f $PIDFILE ]; then
        echo "XFD Discovery Server (should be) running with PID:"
        cat $PIDFILE
        echo ""
    else
        echo "XFD Discovery Server not running (or not started through init.d)"
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/switchgearsXFDDiscoveryServer {start|stop|status|restart}"
    exit 1
    ;;
esac

exit 0
