#!/bin/bash
# /etc/init.d/cloudxfd
# Debian on Raspberry Pi compatible XFD startup script, Device Discovery Server.
# info@switch-gears.dk
#
### BEGIN INIT INFO
# Provides:          cloudxfd_client
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start CloudXFD at boot time
# Description:       Jumpstarts the ZeroMQ client to connect to a Jenkins master from behing a firewall.
### END INIT INFO

DESC="Gitgear.com CloudXFD"
NAME=cloudxfd
SCRIPTNAME=/etc/init.d/$NAME
PIDFILE=/tmp/xfd/cloudxfd.pid

if [ `id -u` -ne 0 ]; then
    echo "The $NAME init script can only be run as root"
    exit 1
fi

do_start()
{
    mkdir -p $(dirname $PIDFILE)
    rm -f $PIDFILE
    sudo /home/pi/extremefeedbacklamp/cloudxfd.py &
    echo -n $! > $PIDFILE
}

do_stop()
{
    if [ -f $PIDFILE ]; then
        kill `cat $PIDFILE`
    fi
}

case "$1" in
  start)
    echo "Starting $NAME"
    do_start
    ;;
  stop)
    echo "Stopping $NAME"
    do_stop
    ;;
  restart)
    echo "Stopping $NAME"
    do_stop
    do_start
    ;;
  status)
    if [ -f $PIDFILE ]; then
        echo "CloudXFD client (should be) running with PID:"
        cat $PIDFILE
        echo ""
    else
        echo "CloudXFD client not running (or not started through init.d)"
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/cloudxfd {start|stop|status|restart}"
    exit 1
    ;;
esac

exit 0
